DATA SEGMENT   
    PORTA EQU 00H
	PCWRD   EQU 06H
    
ENDS
STACK SEGMENT
    DW   128  DUP(0)
ENDS
CODE SEGMENT
START:
    MOV AX, DATA
    MOV DS, AX
    MOV ES, AX  
    
;define IO ports
    MOV DX,PCWRD
    MOV AL,10000000B   ;all ports output
    OUT DX,AL

	TRAFFIC:
    	MOV CX,60000
		CALL DELAY
		MOV AL,88H
		CALL OUTA
		MOV CX,60000
		CALL DELAY
		MOV AL, 50H
		CALL OUTA
		MOV CX, 60000
		CALL DELAY
		MOV AL, 24H
		CALL OUTA
		JMP TRAFFIC

HLT

PROC DELAY
    ;CRUDE DELAY FUNCTION                                
    ;CX=50 means 1ms(BECAUSE LOOP TAKES 17 TICKS) TO BE REPLACED WITH DOS DELAY FUNCTION
	JCXZ DELAYEND
	DELLOOP:
	LOOP DELLOOP	
	DELAYEND:
	RET
ENDP DELAY
PROC OUTA
;PARAMS PASSED IN AL
	PUSH DX
	MOV DX,PORTA
	OUT DX,AL
	POP DX
	RET	
ENDP OUTA
CODE ENDS
END START
